(cl:defpackage manipulation-srv
  (:use )
  (:export
<<<<<<< HEAD
   "ALIGNBASE"
   "<ALIGNBASE-REQUEST>"
   "ALIGNBASE-REQUEST"
   "<ALIGNBASE-RESPONSE>"
   "ALIGNBASE-RESPONSE"
=======
   "EXECUTECOMMAND"
   "<EXECUTECOMMAND-REQUEST>"
   "EXECUTECOMMAND-REQUEST"
   "<EXECUTECOMMAND-RESPONSE>"
   "EXECUTECOMMAND-RESPONSE"
>>>>>>> 0175771262e24e6499a87be41a07a53cb829079b
  ))

