(cl:defpackage manipulation-srv
  (:use )
  (:export
   "ALIGNBASE"
   "<ALIGNBASE-REQUEST>"
   "ALIGNBASE-REQUEST"
   "<ALIGNBASE-RESPONSE>"
   "ALIGNBASE-RESPONSE"
   "EXECUTECOMMAND"
   "<EXECUTECOMMAND-REQUEST>"
   "EXECUTECOMMAND-REQUEST"
   "<EXECUTECOMMAND-RESPONSE>"
   "EXECUTECOMMAND-RESPONSE"
  ))

