; Auto-generated. Do not edit!


(cl:in-package stretch_demos-msg)


;//! \htmlinclude ArucoHeadScanFeedback.msg.html

(cl:defclass <ArucoHeadScanFeedback> (roslisp-msg-protocol:ros-message)
  ((pan_angle
    :reader pan_angle
    :initarg :pan_angle
    :type cl:float
    :initform 0.0))
)

(cl:defclass ArucoHeadScanFeedback (<ArucoHeadScanFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ArucoHeadScanFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ArucoHeadScanFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name stretch_demos-msg:<ArucoHeadScanFeedback> is deprecated: use stretch_demos-msg:ArucoHeadScanFeedback instead.")))

(cl:ensure-generic-function 'pan_angle-val :lambda-list '(m))
(cl:defmethod pan_angle-val ((m <ArucoHeadScanFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader stretch_demos-msg:pan_angle-val is deprecated.  Use stretch_demos-msg:pan_angle instead.")
  (pan_angle m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ArucoHeadScanFeedback>) ostream)
  "Serializes a message object of type '<ArucoHeadScanFeedback>"
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'pan_angle))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ArucoHeadScanFeedback>) istream)
  "Deserializes a message object of type '<ArucoHeadScanFeedback>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'pan_angle) (roslisp-utils:decode-single-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ArucoHeadScanFeedback>)))
  "Returns string type for a message object of type '<ArucoHeadScanFeedback>"
  "stretch_demos/ArucoHeadScanFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ArucoHeadScanFeedback)))
  "Returns string type for a message object of type 'ArucoHeadScanFeedback"
  "stretch_demos/ArucoHeadScanFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ArucoHeadScanFeedback>)))
  "Returns md5sum for a message object of type '<ArucoHeadScanFeedback>"
  "f8d06c64a9db7a2a34a365c076b315f6")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ArucoHeadScanFeedback)))
  "Returns md5sum for a message object of type 'ArucoHeadScanFeedback"
  "f8d06c64a9db7a2a34a365c076b315f6")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ArucoHeadScanFeedback>)))
  "Returns full string definition for message of type '<ArucoHeadScanFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define a feedback message~%~%# Pan angle of the camera~%float32 pan_angle~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ArucoHeadScanFeedback)))
  "Returns full string definition for message of type 'ArucoHeadScanFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define a feedback message~%~%# Pan angle of the camera~%float32 pan_angle~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ArucoHeadScanFeedback>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ArucoHeadScanFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'ArucoHeadScanFeedback
    (cl:cons ':pan_angle (pan_angle msg))
))
