; Auto-generated. Do not edit!


(cl:in-package stretch_demos-msg)


;//! \htmlinclude ArucoHeadScanResult.msg.html

(cl:defclass <ArucoHeadScanResult> (roslisp-msg-protocol:ros-message)
  ((aruco_found
    :reader aruco_found
    :initarg :aruco_found
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass ArucoHeadScanResult (<ArucoHeadScanResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ArucoHeadScanResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ArucoHeadScanResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name stretch_demos-msg:<ArucoHeadScanResult> is deprecated: use stretch_demos-msg:ArucoHeadScanResult instead.")))

(cl:ensure-generic-function 'aruco_found-val :lambda-list '(m))
(cl:defmethod aruco_found-val ((m <ArucoHeadScanResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader stretch_demos-msg:aruco_found-val is deprecated.  Use stretch_demos-msg:aruco_found instead.")
  (aruco_found m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ArucoHeadScanResult>) ostream)
  "Serializes a message object of type '<ArucoHeadScanResult>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'aruco_found) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ArucoHeadScanResult>) istream)
  "Deserializes a message object of type '<ArucoHeadScanResult>"
    (cl:setf (cl:slot-value msg 'aruco_found) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ArucoHeadScanResult>)))
  "Returns string type for a message object of type '<ArucoHeadScanResult>"
  "stretch_demos/ArucoHeadScanResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ArucoHeadScanResult)))
  "Returns string type for a message object of type 'ArucoHeadScanResult"
  "stretch_demos/ArucoHeadScanResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ArucoHeadScanResult>)))
  "Returns md5sum for a message object of type '<ArucoHeadScanResult>"
  "bc8d979150e87116bdefde500a6f1d59")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ArucoHeadScanResult)))
  "Returns md5sum for a message object of type 'ArucoHeadScanResult"
  "bc8d979150e87116bdefde500a6f1d59")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ArucoHeadScanResult>)))
  "Returns full string definition for message of type '<ArucoHeadScanResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the result~%~%# Whether goal aruco ID was found~%bool aruco_found~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ArucoHeadScanResult)))
  "Returns full string definition for message of type 'ArucoHeadScanResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the result~%~%# Whether goal aruco ID was found~%bool aruco_found~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ArucoHeadScanResult>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ArucoHeadScanResult>))
  "Converts a ROS message object to a list"
  (cl:list 'ArucoHeadScanResult
    (cl:cons ':aruco_found (aruco_found msg))
))
