; Auto-generated. Do not edit!


(cl:in-package stretch_demos-msg)


;//! \htmlinclude VisualServoResult.msg.html

(cl:defclass <VisualServoResult> (roslisp-msg-protocol:ros-message)
  ((result
    :reader result
    :initarg :result
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass VisualServoResult (<VisualServoResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <VisualServoResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'VisualServoResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name stretch_demos-msg:<VisualServoResult> is deprecated: use stretch_demos-msg:VisualServoResult instead.")))

(cl:ensure-generic-function 'result-val :lambda-list '(m))
(cl:defmethod result-val ((m <VisualServoResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader stretch_demos-msg:result-val is deprecated.  Use stretch_demos-msg:result instead.")
  (result m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <VisualServoResult>) ostream)
  "Serializes a message object of type '<VisualServoResult>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'result) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <VisualServoResult>) istream)
  "Deserializes a message object of type '<VisualServoResult>"
    (cl:setf (cl:slot-value msg 'result) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<VisualServoResult>)))
  "Returns string type for a message object of type '<VisualServoResult>"
  "stretch_demos/VisualServoResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'VisualServoResult)))
  "Returns string type for a message object of type 'VisualServoResult"
  "stretch_demos/VisualServoResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<VisualServoResult>)))
  "Returns md5sum for a message object of type '<VisualServoResult>"
  "eb13ac1f1354ccecb7941ee8fa2192e8")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'VisualServoResult)))
  "Returns md5sum for a message object of type 'VisualServoResult"
  "eb13ac1f1354ccecb7941ee8fa2192e8")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<VisualServoResult>)))
  "Returns full string definition for message of type '<VisualServoResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# result~%# result is the success flag~%bool result~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'VisualServoResult)))
  "Returns full string definition for message of type 'VisualServoResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# result~%# result is the success flag~%bool result~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <VisualServoResult>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <VisualServoResult>))
  "Converts a ROS message object to a list"
  (cl:list 'VisualServoResult
    (cl:cons ':result (result msg))
))
