; Auto-generated. Do not edit!


(cl:in-package stretch_demos-msg)


;//! \htmlinclude VisualServoGoal.msg.html

(cl:defclass <VisualServoGoal> (roslisp-msg-protocol:ros-message)
  ((target_frame
    :reader target_frame
    :initarg :target_frame
    :type cl:string
    :initform "")
   (source_frame
    :reader source_frame
    :initarg :source_frame
    :type cl:string
    :initform ""))
)

(cl:defclass VisualServoGoal (<VisualServoGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <VisualServoGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'VisualServoGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name stretch_demos-msg:<VisualServoGoal> is deprecated: use stretch_demos-msg:VisualServoGoal instead.")))

(cl:ensure-generic-function 'target_frame-val :lambda-list '(m))
(cl:defmethod target_frame-val ((m <VisualServoGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader stretch_demos-msg:target_frame-val is deprecated.  Use stretch_demos-msg:target_frame instead.")
  (target_frame m))

(cl:ensure-generic-function 'source_frame-val :lambda-list '(m))
(cl:defmethod source_frame-val ((m <VisualServoGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader stretch_demos-msg:source_frame-val is deprecated.  Use stretch_demos-msg:source_frame instead.")
  (source_frame m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <VisualServoGoal>) ostream)
  "Serializes a message object of type '<VisualServoGoal>"
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'target_frame))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'target_frame))
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'source_frame))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'source_frame))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <VisualServoGoal>) istream)
  "Deserializes a message object of type '<VisualServoGoal>"
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'target_frame) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'target_frame) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'source_frame) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'source_frame) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<VisualServoGoal>)))
  "Returns string type for a message object of type '<VisualServoGoal>"
  "stretch_demos/VisualServoGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'VisualServoGoal)))
  "Returns string type for a message object of type 'VisualServoGoal"
  "stretch_demos/VisualServoGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<VisualServoGoal>)))
  "Returns md5sum for a message object of type '<VisualServoGoal>"
  "1cca159d7671f770d19e4e288854c223")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'VisualServoGoal)))
  "Returns md5sum for a message object of type 'VisualServoGoal"
  "1cca159d7671f770d19e4e288854c223")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<VisualServoGoal>)))
  "Returns full string definition for message of type '<VisualServoGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# goal~%# target frame defines the transform frame that needs to be compared with source_frame~%string target_frame~%~%# target frame defines the transform frame that needs to be compared with target_frame~%string source_frame~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'VisualServoGoal)))
  "Returns full string definition for message of type 'VisualServoGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# goal~%# target frame defines the transform frame that needs to be compared with source_frame~%string target_frame~%~%# target frame defines the transform frame that needs to be compared with target_frame~%string source_frame~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <VisualServoGoal>))
  (cl:+ 0
     4 (cl:length (cl:slot-value msg 'target_frame))
     4 (cl:length (cl:slot-value msg 'source_frame))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <VisualServoGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'VisualServoGoal
    (cl:cons ':target_frame (target_frame msg))
    (cl:cons ':source_frame (source_frame msg))
))
