// Auto-generated. Do not edit!

// (in-package stretch_demos.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class VisualServoFeedback {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.angle_error = null;
      this.distance_error = null;
    }
    else {
      if (initObj.hasOwnProperty('angle_error')) {
        this.angle_error = initObj.angle_error
      }
      else {
        this.angle_error = 0.0;
      }
      if (initObj.hasOwnProperty('distance_error')) {
        this.distance_error = initObj.distance_error
      }
      else {
        this.distance_error = 0.0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type VisualServoFeedback
    // Serialize message field [angle_error]
    bufferOffset = _serializer.float64(obj.angle_error, buffer, bufferOffset);
    // Serialize message field [distance_error]
    bufferOffset = _serializer.float64(obj.distance_error, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type VisualServoFeedback
    let len;
    let data = new VisualServoFeedback(null);
    // Deserialize message field [angle_error]
    data.angle_error = _deserializer.float64(buffer, bufferOffset);
    // Deserialize message field [distance_error]
    data.distance_error = _deserializer.float64(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 16;
  }

  static datatype() {
    // Returns string type for a message object
    return 'stretch_demos/VisualServoFeedback';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'b36919b18c17a48cbd98a249a4c96a61';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # feedback
    # angle error is the angular error between source and target frames
    float64 angle_error
    
    # distance error is the euclidean error between source and target frames
    float64 distance_error
    
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new VisualServoFeedback(null);
    if (msg.angle_error !== undefined) {
      resolved.angle_error = msg.angle_error;
    }
    else {
      resolved.angle_error = 0.0
    }

    if (msg.distance_error !== undefined) {
      resolved.distance_error = msg.distance_error;
    }
    else {
      resolved.distance_error = 0.0
    }

    return resolved;
    }
};

module.exports = VisualServoFeedback;
