// Generated by gencpp from file manipulation/AlignBase.msg
// DO NOT EDIT!


#ifndef MANIPULATION_MESSAGE_ALIGNBASE_H
#define MANIPULATION_MESSAGE_ALIGNBASE_H

#include <ros/service_traits.h>


#include <manipulation/AlignBaseRequest.h>
#include <manipulation/AlignBaseResponse.h>


namespace manipulation
{

struct AlignBase
{

typedef AlignBaseRequest Request;
typedef AlignBaseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AlignBase
} // namespace manipulation


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::manipulation::AlignBase > {
  static const char* value()
  {
    return "210b5d0e3d60fa9dac834d90f73f9337";
  }

  static const char* value(const ::manipulation::AlignBase&) { return value(); }
};

template<>
struct DataType< ::manipulation::AlignBase > {
  static const char* value()
  {
    return "manipulation/AlignBase";
  }

  static const char* value(const ::manipulation::AlignBase&) { return value(); }
};


// service_traits::MD5Sum< ::manipulation::AlignBaseRequest> should match
// service_traits::MD5Sum< ::manipulation::AlignBase >
template<>
struct MD5Sum< ::manipulation::AlignBaseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::manipulation::AlignBase >::value();
  }
  static const char* value(const ::manipulation::AlignBaseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::manipulation::AlignBaseRequest> should match
// service_traits::DataType< ::manipulation::AlignBase >
template<>
struct DataType< ::manipulation::AlignBaseRequest>
{
  static const char* value()
  {
    return DataType< ::manipulation::AlignBase >::value();
  }
  static const char* value(const ::manipulation::AlignBaseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::manipulation::AlignBaseResponse> should match
// service_traits::MD5Sum< ::manipulation::AlignBase >
template<>
struct MD5Sum< ::manipulation::AlignBaseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::manipulation::AlignBase >::value();
  }
  static const char* value(const ::manipulation::AlignBaseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::manipulation::AlignBaseResponse> should match
// service_traits::DataType< ::manipulation::AlignBase >
template<>
struct DataType< ::manipulation::AlignBaseResponse>
{
  static const char* value()
  {
    return DataType< ::manipulation::AlignBase >::value();
  }
  static const char* value(const ::manipulation::AlignBaseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MANIPULATION_MESSAGE_ALIGNBASE_H
