// Generated by gencpp from file manipulation/AlignBaseResponse.msg
// DO NOT EDIT!


#ifndef MANIPULATION_MESSAGE_ALIGNBASERESPONSE_H
#define MANIPULATION_MESSAGE_ALIGNBASERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace manipulation
{
template <class ContainerAllocator>
struct AlignBaseResponse_
{
  typedef AlignBaseResponse_<ContainerAllocator> Type;

  AlignBaseResponse_()
    : success(false)  {
    }
  AlignBaseResponse_(const ContainerAllocator& _alloc)
    : success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::manipulation::AlignBaseResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::manipulation::AlignBaseResponse_<ContainerAllocator> const> ConstPtr;

}; // struct AlignBaseResponse_

typedef ::manipulation::AlignBaseResponse_<std::allocator<void> > AlignBaseResponse;

typedef boost::shared_ptr< ::manipulation::AlignBaseResponse > AlignBaseResponsePtr;
typedef boost::shared_ptr< ::manipulation::AlignBaseResponse const> AlignBaseResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::manipulation::AlignBaseResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::manipulation::AlignBaseResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::manipulation::AlignBaseResponse_<ContainerAllocator1> & lhs, const ::manipulation::AlignBaseResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::manipulation::AlignBaseResponse_<ContainerAllocator1> & lhs, const ::manipulation::AlignBaseResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace manipulation

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::manipulation::AlignBaseResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::manipulation::AlignBaseResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::manipulation::AlignBaseResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::manipulation::AlignBaseResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::manipulation::AlignBaseResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::manipulation::AlignBaseResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::manipulation::AlignBaseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::manipulation::AlignBaseResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::manipulation::AlignBaseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "manipulation/AlignBaseResponse";
  }

  static const char* value(const ::manipulation::AlignBaseResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::manipulation::AlignBaseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
;
  }

  static const char* value(const ::manipulation::AlignBaseResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::manipulation::AlignBaseResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AlignBaseResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::manipulation::AlignBaseResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::manipulation::AlignBaseResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MANIPULATION_MESSAGE_ALIGNBASERESPONSE_H
