// Generated by gencpp from file manipulation/ExecuteCommandRequest.msg
// DO NOT EDIT!


#ifndef MANIPULATION_MESSAGE_EXECUTECOMMANDREQUEST_H
#define MANIPULATION_MESSAGE_EXECUTECOMMANDREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace manipulation
{
template <class ContainerAllocator>
struct ExecuteCommandRequest_
{
  typedef ExecuteCommandRequest_<ContainerAllocator> Type;

  ExecuteCommandRequest_()
    : command()  {
    }
  ExecuteCommandRequest_(const ContainerAllocator& _alloc)
    : command(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _command_type;
  _command_type command;





  typedef boost::shared_ptr< ::manipulation::ExecuteCommandRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::manipulation::ExecuteCommandRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ExecuteCommandRequest_

typedef ::manipulation::ExecuteCommandRequest_<std::allocator<void> > ExecuteCommandRequest;

typedef boost::shared_ptr< ::manipulation::ExecuteCommandRequest > ExecuteCommandRequestPtr;
typedef boost::shared_ptr< ::manipulation::ExecuteCommandRequest const> ExecuteCommandRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::manipulation::ExecuteCommandRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::manipulation::ExecuteCommandRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::manipulation::ExecuteCommandRequest_<ContainerAllocator1> & lhs, const ::manipulation::ExecuteCommandRequest_<ContainerAllocator2> & rhs)
{
  return lhs.command == rhs.command;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::manipulation::ExecuteCommandRequest_<ContainerAllocator1> & lhs, const ::manipulation::ExecuteCommandRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace manipulation

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::manipulation::ExecuteCommandRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::manipulation::ExecuteCommandRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::manipulation::ExecuteCommandRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::manipulation::ExecuteCommandRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::manipulation::ExecuteCommandRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::manipulation::ExecuteCommandRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::manipulation::ExecuteCommandRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cba5e21e920a3a2b7b375cb65b64cdea";
  }

  static const char* value(const ::manipulation::ExecuteCommandRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcba5e21e920a3a2bULL;
  static const uint64_t static_value2 = 0x7b375cb65b64cdeaULL;
};

template<class ContainerAllocator>
struct DataType< ::manipulation::ExecuteCommandRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "manipulation/ExecuteCommandRequest";
  }

  static const char* value(const ::manipulation::ExecuteCommandRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::manipulation::ExecuteCommandRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ExecuteCommand.srv\n"
"string command\n"
;
  }

  static const char* value(const ::manipulation::ExecuteCommandRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::manipulation::ExecuteCommandRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.command);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ExecuteCommandRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::manipulation::ExecuteCommandRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::manipulation::ExecuteCommandRequest_<ContainerAllocator>& v)
  {
    s << indent << "command: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.command);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MANIPULATION_MESSAGE_EXECUTECOMMANDREQUEST_H
