// Generated by gencpp from file manipulation/ExecuteCommand.msg
// DO NOT EDIT!


#ifndef MANIPULATION_MESSAGE_EXECUTECOMMAND_H
#define MANIPULATION_MESSAGE_EXECUTECOMMAND_H

#include <ros/service_traits.h>


#include <manipulation/ExecuteCommandRequest.h>
#include <manipulation/ExecuteCommandResponse.h>


namespace manipulation
{

struct ExecuteCommand
{

typedef ExecuteCommandRequest Request;
typedef ExecuteCommandResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ExecuteCommand
} // namespace manipulation


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::manipulation::ExecuteCommand > {
  static const char* value()
  {
    return "cba5e21e920a3a2b7b375cb65b64cdea";
  }

  static const char* value(const ::manipulation::ExecuteCommand&) { return value(); }
};

template<>
struct DataType< ::manipulation::ExecuteCommand > {
  static const char* value()
  {
    return "manipulation/ExecuteCommand";
  }

  static const char* value(const ::manipulation::ExecuteCommand&) { return value(); }
};


// service_traits::MD5Sum< ::manipulation::ExecuteCommandRequest> should match
// service_traits::MD5Sum< ::manipulation::ExecuteCommand >
template<>
struct MD5Sum< ::manipulation::ExecuteCommandRequest>
{
  static const char* value()
  {
    return MD5Sum< ::manipulation::ExecuteCommand >::value();
  }
  static const char* value(const ::manipulation::ExecuteCommandRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::manipulation::ExecuteCommandRequest> should match
// service_traits::DataType< ::manipulation::ExecuteCommand >
template<>
struct DataType< ::manipulation::ExecuteCommandRequest>
{
  static const char* value()
  {
    return DataType< ::manipulation::ExecuteCommand >::value();
  }
  static const char* value(const ::manipulation::ExecuteCommandRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::manipulation::ExecuteCommandResponse> should match
// service_traits::MD5Sum< ::manipulation::ExecuteCommand >
template<>
struct MD5Sum< ::manipulation::ExecuteCommandResponse>
{
  static const char* value()
  {
    return MD5Sum< ::manipulation::ExecuteCommand >::value();
  }
  static const char* value(const ::manipulation::ExecuteCommandResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::manipulation::ExecuteCommandResponse> should match
// service_traits::DataType< ::manipulation::ExecuteCommand >
template<>
struct DataType< ::manipulation::ExecuteCommandResponse>
{
  static const char* value()
  {
    return DataType< ::manipulation::ExecuteCommand >::value();
  }
  static const char* value(const ::manipulation::ExecuteCommandResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MANIPULATION_MESSAGE_EXECUTECOMMAND_H
