// Generated by gencpp from file stretch_demos/VisualServoResult.msg
// DO NOT EDIT!


#ifndef STRETCH_DEMOS_MESSAGE_VISUALSERVORESULT_H
#define STRETCH_DEMOS_MESSAGE_VISUALSERVORESULT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace stretch_demos
{
template <class ContainerAllocator>
struct VisualServoResult_
{
  typedef VisualServoResult_<ContainerAllocator> Type;

  VisualServoResult_()
    : result(false)  {
    }
  VisualServoResult_(const ContainerAllocator& _alloc)
    : result(false)  {
  (void)_alloc;
    }



   typedef uint8_t _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::stretch_demos::VisualServoResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::stretch_demos::VisualServoResult_<ContainerAllocator> const> ConstPtr;

}; // struct VisualServoResult_

typedef ::stretch_demos::VisualServoResult_<std::allocator<void> > VisualServoResult;

typedef boost::shared_ptr< ::stretch_demos::VisualServoResult > VisualServoResultPtr;
typedef boost::shared_ptr< ::stretch_demos::VisualServoResult const> VisualServoResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::stretch_demos::VisualServoResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::stretch_demos::VisualServoResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::stretch_demos::VisualServoResult_<ContainerAllocator1> & lhs, const ::stretch_demos::VisualServoResult_<ContainerAllocator2> & rhs)
{
  return lhs.result == rhs.result;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::stretch_demos::VisualServoResult_<ContainerAllocator1> & lhs, const ::stretch_demos::VisualServoResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace stretch_demos

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::stretch_demos::VisualServoResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::stretch_demos::VisualServoResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::stretch_demos::VisualServoResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::stretch_demos::VisualServoResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::stretch_demos::VisualServoResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::stretch_demos::VisualServoResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::stretch_demos::VisualServoResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "eb13ac1f1354ccecb7941ee8fa2192e8";
  }

  static const char* value(const ::stretch_demos::VisualServoResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xeb13ac1f1354ccecULL;
  static const uint64_t static_value2 = 0xb7941ee8fa2192e8ULL;
};

template<class ContainerAllocator>
struct DataType< ::stretch_demos::VisualServoResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "stretch_demos/VisualServoResult";
  }

  static const char* value(const ::stretch_demos::VisualServoResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::stretch_demos::VisualServoResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# result\n"
"# result is the success flag\n"
"bool result\n"
"\n"
;
  }

  static const char* value(const ::stretch_demos::VisualServoResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::stretch_demos::VisualServoResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct VisualServoResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::stretch_demos::VisualServoResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::stretch_demos::VisualServoResult_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // STRETCH_DEMOS_MESSAGE_VISUALSERVORESULT_H
