# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from stretch_demos/ArucoHeadScanGoal.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class ArucoHeadScanGoal(genpy.Message):
  _md5sum = "7c9f72de60496d5ea3903a808d86da58"
  _type = "stretch_demos/ArucoHeadScanGoal"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
# Define the goal

# Specify aruco ID to look for
uint32 aruco_id

# Specify the camera tilt_angle at which to scan
float32 tilt_angle

# Publish tf relative to the map frame
bool publish_to_map

# If robot should rotate to cover the blind spot generated by the mast
bool fill_in_blindspot_with_second_scan 

# If scan should stop as soon as a matching aruco ID is found
bool fast_scan

"""
  __slots__ = ['aruco_id','tilt_angle','publish_to_map','fill_in_blindspot_with_second_scan','fast_scan']
  _slot_types = ['uint32','float32','bool','bool','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       aruco_id,tilt_angle,publish_to_map,fill_in_blindspot_with_second_scan,fast_scan

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ArucoHeadScanGoal, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.aruco_id is None:
        self.aruco_id = 0
      if self.tilt_angle is None:
        self.tilt_angle = 0.
      if self.publish_to_map is None:
        self.publish_to_map = False
      if self.fill_in_blindspot_with_second_scan is None:
        self.fill_in_blindspot_with_second_scan = False
      if self.fast_scan is None:
        self.fast_scan = False
    else:
      self.aruco_id = 0
      self.tilt_angle = 0.
      self.publish_to_map = False
      self.fill_in_blindspot_with_second_scan = False
      self.fast_scan = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_If3B().pack(_x.aruco_id, _x.tilt_angle, _x.publish_to_map, _x.fill_in_blindspot_with_second_scan, _x.fast_scan))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 11
      (_x.aruco_id, _x.tilt_angle, _x.publish_to_map, _x.fill_in_blindspot_with_second_scan, _x.fast_scan,) = _get_struct_If3B().unpack(str[start:end])
      self.publish_to_map = bool(self.publish_to_map)
      self.fill_in_blindspot_with_second_scan = bool(self.fill_in_blindspot_with_second_scan)
      self.fast_scan = bool(self.fast_scan)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_If3B().pack(_x.aruco_id, _x.tilt_angle, _x.publish_to_map, _x.fill_in_blindspot_with_second_scan, _x.fast_scan))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 11
      (_x.aruco_id, _x.tilt_angle, _x.publish_to_map, _x.fill_in_blindspot_with_second_scan, _x.fast_scan,) = _get_struct_If3B().unpack(str[start:end])
      self.publish_to_map = bool(self.publish_to_map)
      self.fill_in_blindspot_with_second_scan = bool(self.fill_in_blindspot_with_second_scan)
      self.fast_scan = bool(self.fast_scan)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_If3B = None
def _get_struct_If3B():
    global _struct_If3B
    if _struct_If3B is None:
        _struct_If3B = struct.Struct("<If3B")
    return _struct_If3B
